name: Build and Push Docker Compose Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    environment: firecrawl
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Set up Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Build and push Docker Compose images
        run: |
          docker-compose -f docker-compose.yaml build
          docker-compose -f docker-compose.yaml push
